# Welcome to Jekyll!

# Website settings
title: Arthur Diniz
description: Arthur's site.
keywords: github,gh-pages
baseurl:
url: http://www.arthurbdiniz.com  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Arthur Diniz  # Be used at blog posts' author.
  first_name: Arthur  # Be used at index page about me section.
  last_name: Diniz  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: arthurbdiniz  # Leave blank if you don't have now
  linkedin_id: arthurbdiniz # Leave blank if you don't have now
  #facebook_username: jiakunnj  # Leave blank if you don't have now
  #twitter_username: jiakun614  # Leave blank if you don't have now
  email: me@arthurbdiniz.com  # Leave blank if you don't have now
  # cv: http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  desc: I am a DevOps/Site Reliability Engineer (SRE) with experience in APIs, infrastructure automation, and scripting.

# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: arthurbdiniz

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-172718904-1

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# URL settings
permalink: blog/:title.html
